version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Sincroniza tu código local con el contenedor
      - ./backend:/app
    # Le dice a Docker exactamente cómo arrancar tu main.py real con Hot Reload activo
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Evita que tu carpeta node_modules local sobrescriba la del contenedor
      - /app/node_modules