version: '3.8'

services:
  backend:
    build: 
      context: ./backend
    ports:
      - "8000:8000"
    volumes:
      # Esto sincroniza tu código local con el contenedor para que veas los cambios en vivo (Hot Reload)
      - ./backend:/app
    environment:
      - PYTHONUNBUFFERED=1

  frontend:
    build: 
      context: ./frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      # Esta línea evita que tu carpeta node_modules local sobrescriba la del contenedor
      - /app/node_modules